### ISSUE TITLE
Disable animations for step and button

### ISSUE THREAD

**Issue by sum1190** [JoxieMedina/ionic2-simple-conditional-wizard#3]
Hi, is it possible to disable animation for step and button? I've tried to pass null in the @Component attribute "animations" but I've got some error on browser console.

Thank you,
Davide.

**Comment by JoxieMedina** [comment]
Hi, in this component the animations also controls when the step is showing or not, so in order to have no animations when change of step you need create an animations too , like this:

```` 
static none = [
        trigger('WizardAnimations', [
            state('enter', style({ position: 'relative', top: 0 ,width:'100%'})),
            state('leave', style({ display: 'none', position: 'relative', top: 0 }))
        ])
    ];
````
you can insert the above code in the file `ion-simple-wizard-animations.ts` and in the file `ion-simple-wizard.step.component.ts` change the animation to none, like this: ` animations: WizardAnimations.none` and it's the same for the button , create a new state in the animations file : 
````
 static btn_none = [
        trigger('btnState', [
            state('enter', style({ position: 'relative', top: 0 ,width:'100%'})),
            state('leave', style({ display: 'none', position: 'relative', top: 0 }))
        ])
    ];
````
and in the file `ion-simple-wizard.component.ts` change the animation to this `animations: WizardAnimations.btn_none`

Greetings

**Comment by sum1190** [comment]
Thank you :)
